### ISSUE TITLE
bazel sandboxing is broken

### ISSUE THREAD

**Issue by alexeagle** [alexeagle/ngcontainer#1]
This is true for other docker images also, eg.
https://github.com/bazelbuild/bazel/issues/1972#issuecomment-304053625

Either need to change the debian kernel, or run the docker container with --privileged, or find a way to workaround /proc/xen.

Another workaround is to disable sandboxing.

**Comment by Rudd-O** [comment]
This is also broken in Qubes OS, for the reason that `/proc/xen` is mounted.

Forgive me if this question is impertinent:

Is there a workaround that **does not** require root privileges?

Thank you.  Let's make Qubes OS work again!

**Comment by alexeagle** [comment]
I haven't found a workaround yet, watch that linked issue?

**Comment by alexeagle** [comment]
Looks like https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/bazel might work, need to test it

**Comment by alexeagle** [comment]
Not sure what changed, but it works for me now. Likely fixed in a bazel update (now on 0.5.4)

https://circleci.com/gh/alexeagle/tsickle/17
