### ISSUE TITLE
too slow to pull docker image in each CircleCI run

### ISSUE THREAD

**Issue by alexeagle** [alexeagle/ngcontainer#2]
Currently we spend about 20-25s pulling the docker layers on each circle run, which is way too much.

See https://github.com/gregmagolan/circleci-build-container/blob/master/Dockerfile for a nearly equivalent image that boots faster.

/cc @gregmagolan

**Comment by alexeagle** [comment]
Problem gets worse as ngcontainer gets bigger. Adding buildifier yesterday made the image 100M bigger, why?
Greg, can you own this one?
/cc @mattmoor is our docker expert, are there general resources on the web for keeping our image small?

**Comment by gregmagolan** [comment]
Yup. I can own this.

It may improve things to use a CircleCI node:x.x.x-browsers base image that they maintain. I've found this image is more often cached which speeds up the boot to under 5 seconds when it is. You still get the random case of it not being cached (depending on the worker machine) in which case its no improvement as the image is still large. On the plus side, it comes with Chrome and Firefox installed so the only things that are needed on top of that are the Java SDK, Bazel and brotolli.

**Comment by gregmagolan** [comment]
Example: https://github.com/gregmagolan/circleci-build-container

**Comment by alexeagle** [comment]
Note, I added buildifier here in the last commit, but in practice that's not great, because users need to run the formatter locally, and it's hard for them to get the right version of buildifier.

Would be better if users could just `bazel run :buildifier` in their repo locally, and then `bazel run :buildifier.check` could be the command on CI, without needing it in the docker image.

**Comment by alexeagle** [comment]
We are now based on the circleCI base image, so there's nothing more to do here. I've observed both fast and slow setups, which is consistent with some cache hits and some misses.
