### ISSUE TITLE
'latest' tag on docker hub points to 0.0.x? (not 0.0.5)

### ISSUE THREAD

**Issue by dherges** [alexeagle/ngcontainer#4]
Hi Alex,

the 'latest' tag on docker hub points to 0.0.1 (maybe?). When I pull `:0.0.5` I get a different image as compared to the latest.

Is that intended?

```bash
$ docker pull angular/ngcontainer
Using default tag: latest
latest: Pulling from angular/ngcontainer
Digest: sha256:95dbbd8b6114e2bae54ab745fa0aebc9f7f1ec934a206b76ce5147bfe8475a5d
Status: Downloaded newer image for angular/ngcontainer:latest

$ docker pull angular/ngcontainer:0.0.5
0.0.5: Pulling from angular/ngcontainer
3de546fb9d8f: Already exists
bcd6531038d3: Extracting [==================================================>]  157.9MB/157.9MB
8a076b6cf71a: Download complete
173629d1cd68: Download complete
```

**Comment by alexeagle** [comment]
nope, I didn't know I was supposed to advance the 'latest' tag. Do you have a minute to open a PR on publish.sh in this repo?

**Comment by dherges** [comment]
Yes, I copied the docker commands from another project. The safe thing is to tag and push images with both ":VERSION" and ":latest" tag.
