### ISSUE TITLE
NPM global folder is not part of $PATH

### ISSUE THREAD

**Issue by filipesilva** [alexeagle/ngcontainer#8]
Installing global packages is working with `ngcontainer:0.1.0` but the npm bin path doesn't seem to be correctly set.

The following log is taking from a circleci job using `ngcontainer:0.1.0`, debugging via ssh. You can see that globally installing `source-map-explorer` works, but `which source-map-explorer` or `source-map-explorer -v` does not. Printing `$PATH` shows the bin path is not there.

https://github.com/alexeagle/ngcontainer/commit/2109310a763fce391e228ad24b62dde2100a26bb correctly writes to `~/.profile` though, it just doesn't seem like it's used.

```
circleci@bde7a060d55c:~/angular-cli$ npm install -g source-map-explorer
/home/circleci/.npm-global/bin/source-map-explorer -> /home/circleci/.npm-global/lib/node_modules/source-map-explorer/index.js
+ source-map-explorer@1.5.0
added 21 packages in 0.996s
circleci@bde7a060d55c:~/angular-cli$ which source-map-explorer
circleci@bde7a060d55c:~/angular-cli$ source-map-explorer -v
bash: source-map-explorer: command not found
circleci@bde7a060d55c:~/angular-cli$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
circleci@bde7a060d55c:~/angular-cli$ cat ~/.profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
export PATH=~/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by alexeagle** [comment]
Seems to work for me:

```
local$ docker run --rm -it angular/ngcontainer:0.1.0
$ npm install -g @bazel/ibazel
$ ibazel
iBazel - Version v0.2.0
$ echo $PATH
/home/circleci/.npm-global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

But your circleCI log shows that it's not in the PATH on circleCI, maybe they set something after starting the docker container? I see in the top of the circle log:
```
Using build environment variables:
  BASH_ENV=/tmp/.bash_env-5a4f7299c9e77c00010f7414-0-build
...
```

This makes me think that CircleCI runs a clean environment that doesn't inherit environment variables like $PATH.

https://circleci.com/docs/2.0/env-vars/#adding-environment-variables-to-a-container
but we don't want to add a variable. We just want to set the $PATH. https://discuss.circleci.com/t/how-to-add-a-path-to-path-in-circle-2-0/11554/4 looks more promising:

```
job:
  environment:
    BASH_ENV: ~/.profile
```

**Comment by alexeagle** [comment]
@filipesilva did that resolution work for you? can we close this?

**Comment by filipesilva** [comment]
@alexeagle I just tried it and global npm packages were resolved correctly. I don't know if there are other side effects though.
